### ISSUE TITLE
能否增加在新标签页中打开书签呢

### ISSUE THREAD

**Issue by yihanglee-cn** [Alanrk/TabMark-Bookmark-New-Tab#1]
插件很好看，也很实用，希望增加一个在新标签页中打开书签的功能😊

**Comment by Alanrk** [comment]
![image](https://github.com/user-attachments/assets/3538c58f-2fa4-4464-aedf-b14f1043da68)
你指的是点击书签卡片在新标签页打开单个书签吗，如果是这个功能的话，右键第一个就是在新标签页打开

**Comment by Alanrk** [comment]
> 插件很好看，也很实用，希望增加一个在新标签页中打开书签的功能😊
你指的是点击书签卡片在新标签页打开单个书签吗，如果是这个功能的话，右键在书签卡片第一个就是在新标签页打开
![388347288-3538c58f-2fa4-4464-aedf-b14f1043da68](https://github.com/user-attachments/assets/d4d00938-e8e1-461d-97ad-8155a6373860)

**Comment by yihanglee-cn** [comment]
> > 插件很好看，也很实用，希望增加一个在新标签页中打开书签的功能😊
> > 你指的是点击书签卡片在新标签页打开单个书签吗，如果是这个功能的话，右键在书签卡片第一个就是在新标签页打开
> > ![388347288-3538c58f-2fa4-4464-aedf-b14f1043da68](https://private-user-images.githubusercontent.com/48584587/388374395-d4d00938-e8e1-461d-97ad-8155a6373860.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzk1ODIsIm5iZiI6MTczMjE3OTI4MiwicGF0aCI6Ii80ODU4NDU4Ny8zODgzNzQzOTUtZDRkMDA5MzgtZThlMS00NjFkLTk3YWQtODE1NWE2MzczODYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA4NTQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNTQ5NzcwODZjMDYxNTA2MTJjNDQxOGZhNjllNjMzMjVhMGRlYTZhZTEzZGI5NzVkZWM2ZDk1YWQ2ZjEyYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xygOy5g81h27LHqihPg-H5JKWxQMerbgeFjDkb9cnYs)

我是想说直接左键点击书签就可以在新标签页打开😂

**Comment by Alanrk** [comment]
> > > 插件很好看，也很实用，希望增加一个在新标签页中打开书签的功能😊
> > > 你指的是点击书签卡片在新标签页打开单个书签吗，如果是这个功能的话，右键在书签卡片第一个就是在新标签页打开
> > > ![388347288-3538c58f-2fa4-4464-aedf-b14f1043da68](https://private-user-images.githubusercontent.com/48584587/388374395-d4d00938-e8e1-461d-97ad-8155a6373860.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzk1ODIsIm5iZiI6MTczMjE3OTI4MiwicGF0aCI6Ii80ODU4NDU4Ny8zODgzNzQzOTUtZDRkMDA5MzgtZThlMS00NjFkLTk3YWQtODE1NWE2MzczODYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA4NTQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNTQ5NzcwODZjMDYxNTA2MTJjNDQxOGZhNjllNjMzMjVhMGRlYTZhZTEzZGI5NzVkZWM2ZDk1YWQ2ZjEyYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xygOy5g81h27LHqihPg-H5JKWxQMerbgeFjDkb9cnYs)
> 
> 我是想说直接左键点击书签就可以在新标签页打开😂

也许可以加一个配置在设置里面，不过你先右键使用吧。我是这样考虑的：比如a是我的插件页面，你在a页面打开了b、c、d三个书签页面，这个时候你再想打开页面，你还得回去找a页面或者再新打开一个 a页面，这样要不a页面越来越多，要不就是页面多了，回去找 a页面麻烦。所以我设计打开书签默认是在当前页面打开，这样就关闭了a页面，你再想打开页面就新打开一个 a页面，这样能减少tab
